// NWPharmaTech integration module "evidence-library". Generated by build.py from src/assets/js/site.js; do not edit.
// Acts only inside [data-nwpt-module="evidence-library"]; loaded as a file, so the page needs no inline script.
(function () {
  "use strict";
  var init = function () {
    document.querySelectorAll('[data-nwpt-module="evidence-library"]').forEach(function (root) {
      if (root.hasAttribute("data-nwpt-ready")) return;
      root.setAttribute("data-nwpt-ready", "");
      // Evidence filters. Without JavaScript every section is shown, grouped by topic.
      var bar = root.querySelector(".nwpt-filters");
      if (bar) {
        bar.hidden = false;
        var status = root.querySelector(".nwpt-filter-status");
        var sections = root.querySelectorAll(".nwpt-lib-section");
        var apply = function (btn) {
          var f = btn.getAttribute("data-filter");
          bar.querySelectorAll("button[data-filter]").forEach(function (b) { b.setAttribute("aria-pressed", String(b === btn)); });
          var shown = 0;
          sections.forEach(function (s) {
            var on = f === "all" || s.getAttribute("data-section") === f;
            s.hidden = !on;
            if (on) shown += s.querySelectorAll(".nwpt-study-card").length;
          });
          if (status) status.textContent = "Showing " + shown + (shown === 1 ? " source" : " sources") + (f === "all" ? "" : " in " + btn.firstChild.textContent.trim());
        };
        bar.addEventListener("click", function (e) {
          var btn = e.target.closest("button[data-filter]");
          if (btn && bar.contains(btn)) apply(btn);
        });
        // A link to a card in a topic the filter hides shows every topic again, so the page can move to the card.
        var reveal = function (hash) {
          var id;
          try { id = decodeURIComponent(hash.slice(1)); } catch (err) { return false; }
          var el = id && document.getElementById(id);
          var s = el && root.contains(el) ? el.closest(".nwpt-lib-section") : null;
          var all = bar.querySelector('button[data-filter="all"]');
          if (!s || !s.hidden || !all) return false;
          apply(all);
          return el;
        };
        // Any link on this page to one of the module's cards, inside the module or anywhere else on the live page
        // (capture: before the browser follows it).
        document.addEventListener("click", function (e) {
          var a = e.target.closest && e.target.closest("a[href]");
          if (a && a.hash && a.origin === location.origin && a.pathname === location.pathname) reveal(a.hash);
        }, true);
        window.addEventListener("hashchange", function () {
          var el = reveal(location.hash);   // a link from elsewhere on the page: the browser found nothing to show
          if (el) el.scrollIntoView();
        });
      }
    });
  };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
