// NWPharmaTech integration module "evidence-library". Generated by build.py from src/assets/js/site.js; do not edit.
// Acts only inside [data-nwpt-module="evidence-library"]; loaded as a file, so the page needs no inline script.
(function () {
  "use strict";
  var init = function () {
    document.querySelectorAll('[data-nwpt-module="evidence-library"]').forEach(function (root) {
      if (root.hasAttribute("data-nwpt-ready")) return;
      root.setAttribute("data-nwpt-ready", "");
      // Evidence filters. Without JavaScript every section is shown, grouped by topic.
      var bar = root.querySelector(".nwpt-filters");
      if (bar) {
        bar.hidden = false;
        var status = root.querySelector(".nwpt-filter-status");
        var sections = root.querySelectorAll(".nwpt-lib-section");
        bar.addEventListener("click", function (e) {
          var btn = e.target.closest("button[data-filter]");
          if (!btn || !bar.contains(btn)) return;
          var f = btn.getAttribute("data-filter");
          bar.querySelectorAll("button[data-filter]").forEach(function (b) { b.setAttribute("aria-pressed", String(b === btn)); });
          var shown = 0;
          sections.forEach(function (s) {
            var on = f === "all" || s.getAttribute("data-section") === f;
            s.hidden = !on;
            if (on) shown += s.querySelectorAll(".nwpt-study-card").length;
          });
          if (status) status.textContent = "Showing " + shown + (shown === 1 ? " source" : " sources") + (f === "all" ? "" : " in " + btn.firstChild.textContent.trim());
        });
      }
    });
  };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
