// Imports a supplied visual package (unpacked) into the site:
//   node import-visuals.mjs <unpacked-package-dir>
// Packages: the DAO visual tranche (NWPT-DAO-visual-tranche-01.zip -> content/dao-images.json, img/dao/) and the
// first scientific portfolio (NWPT-visual-portfolio-01.zip -> content/portfolio-images.json, img/portfolio/).
// - verifies SHA256SUMS.txt;
// - copies only the web/ WebP derivatives of the images used (never the brief, prompts, masters or the ZIP);
// - makes deliberate 4:3 mobile crops from the masters around each image's focal point (manifest focalPosition);
// - writes content/dao-images.json with every file's intrinsic size, for {{block:dao_image:<id>}}.
// DAO image 15 (the governance diagram raster) is not imported: the diagram is rebuilt as HTML (funding-use.html).
// Portfolio image 03 (micelle field) is not imported, as on the live site; 07 is held (docs/nwpt-031-release.md).
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const sharp = createRequire(import.meta.url)("sharp");
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = path.resolve(process.argv[2] || "");
const PACKAGES = {
  "dao-assets-manifest.json": { dir: "dao", json: "dao-images.json",
    doc: "Generated by tools/import-visuals.mjs from NWPT-DAO-visual-tranche-01.zip (Manus, 24 Sep 2026). Conceptual imagery for proposed and informational content; captions are the site's wording. Rendered by {{block:dao_image:<id>}}.",
    label: "NWPT-DAO-visual-tranche-01" },
  "assets-manifest.json": { dir: "portfolio", json: "portfolio-images.json",
    doc: "Generated by tools/import-visuals.mjs from NWPT-visual-portfolio-01.zip (Manus, 24 Sep 2026). Conceptual scientific imagery; captions are the package's own. Rendered by {{block:dao_image:<id>}}.",
    label: "NWPT-visual-portfolio-01" },
};
const mf = Object.keys(PACKAGES).find((f) => fs.existsSync(path.join(pkg, f)));
if (!mf) { console.error("usage: node import-visuals.mjs <unpacked-package-dir>"); process.exit(2); }
const P = PACKAGES[mf];

const bad = fs.readFileSync(path.join(pkg, "SHA256SUMS.txt"), "utf8").trim().split("\n").filter((l) => {
  const [sum, file] = l.trim().split(/\s+\*?/);
  return crypto.createHash("sha256").update(fs.readFileSync(path.join(pkg, file))).digest("hex") !== sum;
});
if (bad.length) { console.error("checksum mismatch:\n" + bad.join("\n")); process.exit(1); }

const USE = {   // id -> how the site uses it (captions are the site's own wording where the package's would overstate)
  "09-dao-bounded-governance-hero": { role: "explanatory", caption: "Conceptual illustration of the proposed structure." },
  "10-register-digital-twin": { role: "explanatory", caption: "Conceptual illustration: a legal register and a lighter digital record derived from it." },
  "11-clinical-governance-firewall": { role: "explanatory", caption: "Conceptual illustration of independent clinical oversight." },
  "12-milestone-release-architecture": { role: "explanatory", caption: "Conceptual illustration of money released in stages for research work." },
  "13-community-research-commons": { role: "explanatory", caption: "Conceptual illustration of open research dialogue." },
  "14-bounded-governance-sigil": { role: "decorative" },
  // portfolio: the package's captions (explicitly conceptual; no efficacy or delivery claim)
  "01-neural-hero-ultrawide": { role: "explanatory" },
  "02-softgel-cutaway-dark": { role: "explanatory" },
  "04-formulation-light": { role: "explanatory" },
  "05-research-network": { role: "explanatory" },
  "06-programme-horizon": { role: "explanatory" },
  "08-softgel-isolated-transparent": { role: "explanatory" },
};
const manifest = JSON.parse(fs.readFileSync(path.join(pkg, mf), "utf8"));
const out = path.join(root, "src", "assets", "img", P.dir);
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const images = {};
for (const a of manifest.assets) {
  const use = USE[a.id];
  if (!use) continue;
  const files = [];
  for (const rel of a.responsive) {
    const name = path.basename(rel);
    fs.copyFileSync(path.join(pkg, rel), path.join(out, name));
    const m = await sharp(path.join(out, name)).metadata();
    files.push({ file: `${P.dir}/${name}`, width: m.width, height: m.height });
  }
  files.sort((x, y) => x.width - y.width);
  const mobile = [];
  if (use.role === "explanatory") {   // 4:3 crop around the focal point, for narrow screens
    const src = path.join(pkg, a.master);
    const m = await sharp(src).metadata();
    const [fx] = a.focalPosition.split(/\s+/).map((v) => parseFloat(v) / 100);
    const h = m.height, w = Math.min(m.width, Math.round(h * 4 / 3));
    const left = Math.max(0, Math.min(m.width - w, Math.round(fx * m.width - w / 2)));
    for (const tw of [480, 800]) {
      const name = `${a.id}-m${tw}.webp`;
      await sharp(src).extract({ left, top: 0, width: w, height: h }).resize({ width: tw }).webp({ quality: 70 }).toFile(path.join(out, name));
      const mm = await sharp(path.join(out, name)).metadata();
      mobile.push({ file: `${P.dir}/${name}`, width: mm.width, height: mm.height });
    }
  }
  images[a.id] = { role: use.role, alt: use.role === "decorative" ? "" : a.alt, caption: use.role === "decorative" ? null : (use.caption || a.caption),
    focal: a.focalPosition, files, mobile, source: `${P.label} (${manifest.version}), ${a.id}` };
}
const doc = { _doc: P.doc, images };
fs.writeFileSync(path.join(root, "content", P.json), JSON.stringify(doc, null, 1) + "\n");
const total = fs.readdirSync(out).reduce((n, f) => n + fs.statSync(path.join(out, f)).size, 0);
console.log(`imported ${Object.keys(images).length} images, ${fs.readdirSync(out).length} files, ${Math.round(total / 1024)} KB`);
